apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-lua.fullname" . }}
  labels:
    {{- include "nginx-lua.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if not .Values.config.tlsTerminateAtIngress }}
    - port: {{ .Values.service.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "nginx-lua.selectorLabels" . | nindent 4 }}
