apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-stream.fullname" . }}
  labels:
    {{- include "nginx-stream.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "nginx-stream.selectorLabels" . | nindent 4 }}
